### PR TITLE
Check and add TLS 1.2 to ServicePointManager.SecurityProtocol if miss…

### PR DESCRIPTION
**Pull request by regexen**
…ing, instead of replacing existing configuration

Proposed fix for #25

### CODE REVIEW

**Comment by nickalbrecht** [comment]
Yeah, I need this to be applied before I can migrate away from the Beanstream package. I have other API's that I'm using, and I can't have this one forcing the entire application to ONLY allow TLS 1.2. Need to have this corrected (as suggested to use flags) instead of outright blowing away the existing `ServicePointManager.SecurityProtocol` configuration.

**Comment by tulbox** [comment]
With the switch to TLS 1.2 in just a couple days and no commits since Feb 27, why is this item still outstanding? Dropping the ball here Bambora.

**Comment by draganblagojevic** [comment]
Thanks @regexen

**Comment by nickalbrecht** [comment]
> Literally tags everyone I can find who might be able to surface this issue, BEFORE the 1.2 TLS deadline

@svenresch @blazed @fygge @storkie @bowens-bambora @Lmasniuk

**Pull request merged**
